export const WEATHER_TRANSLATIONS = {
    "200": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas com Chuva Fraca" },
    "201": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas com Chuva" },
    "202": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas com Chuva Forte" },
    "210": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas Leves" },
    "211": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas" },
    "212": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas Fortes" },
    "221": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas Irregulares" },
    "230": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas com Chuvisco Leve" },
    "231": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas com Chuvisco" },
    "232": { main: "Thunderstorm", icon: "mdi-weather-lightning", readableName: "Trovoadas com Chuvisco Forte" },
    "300": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuvisco de Intensidade Leve" },
    "301": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuvisco" },
    "302": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuvisco de Intensidade Forte" },
    "310": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuvisco de Intensidade Leve" },
    "311": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuvisco" },
    "312": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuvisco de Intensidade Forte" },
    "313": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuva com Chuvisco" },
    "314": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuva Forte com Chuvisco" },
    "321": { main: "Drizzle", icon: "mdi-weather-pouring", readableName: "Chuvisco" },
    "500": { main: "Rain", icon: "mdi-weather-rainy", readableName: "Chuva Fraca" },
    "501": { main: "Rain", icon: "mdi-weather-rainy", readableName: "Chuva Moderada" },
    "502": { main: "Rain", icon: "mdi-weather-rainy", readableName: "Chuva Intensa" },
    "503": { main: "Rain", icon: "mdi-weather-rainy", readableName: "Chuva Muito Intensa" },
    "504": { main: "Rain", icon: "mdi-weather-rainy", readableName: "Chuva Extrema" },
    "511": { main: "Rain", icon: "mdi-weather-snowy-rainy", readableName: "Chuva Congelante" },
    "520": { main: "Rain", icon: "mdi-weather-pouring", readableName: "Chuva de Intensidade Leve" },
    "521": { main: "Rain", icon: "mdi-weather-pouring", readableName: "Chuva" },
    "522": { main: "Rain", icon: "mdi-weather-pouring", readableName: "Chuva de Intensidade Forte" },
    "531": { main: "Rain", icon: "mdi-weather-pouring", readableName: "Chuva Irregular" },
    "600": { main: "Snow", icon: "mdi-snowflake", readableName: "Neve Leve" },
    "601": { main: "Snow", icon: "mdi-snowflake", readableName: "Neve" },
    "602": { main: "Snow", icon: "mdi-weather-snowy-heavy", readableName: "Neve Forte" },
    "611": { main: "Snow", icon: "mdi-snowflake", readableName: "Neve Mista com Chuva" },
    "612": { main: "Snow", icon: "mdi-weather-snowy-rainy", readableName: "Chuva com Neve de Intensidade Leve" },
    "613": { main: "Snow", icon: "mdi-weather-snowy-rainy", readableName: "Chuva com Neve" },
    "615": { main: "Snow", icon: "mdi-weather-snowy-rainy", readableName: "Chuva e Neve Leve" },
    "616": { main: "Snow", icon: "mdi-weather-snowy-rainy", readableName: "Chuva e Neve" },
    "620": { main: "Snow", icon: "mdi-weather-snowy-rainy", readableName: "Neve Leve" },
    "621": { main: "Snow", icon: "mdi-weather-snowy-rainy", readableName: "Neve" },
    "622": { main: "Snow", icon: "mdi-weather-snowy-rainy", readableName: "Neve Forte" },
    "701": { main: "Mist", icon: "mdi-weather-fog", readableName: "Névoa" },
    "711": { main: "Smoke", icon: "mdi-weather-fog", readableName: "Fumaça" },
    "721": { main: "Haze", icon: "mdi-weather-hazy", readableName: "Neblina" },
    "731": { main: "Dust", icon: "mdi-weather-dust", readableName: "Redemoinhos de Areia/Poeira" },
    "741": { main: "Fog", icon: "mdi-weather-fog", readableName: "Névoa" },
    "751": { main: "Sand", icon: "mdi-weather-dust", readableName: "Areia" },
    "761": { main: "Dust", icon: "mdi-weather-dust", readableName: "Poeira" },
    "762": { main: "Ash", icon: "mdi-weather-dust", readableName: "Cinzas Vulcânicas" },
    "771": { main: "Squall", icon: "mdi-weather-dust", readableName: "Rajadas de Vento" },
    "781": { main: "Tornado", icon: "mdi-weather-tornado", readableName: "Tornado" },
    "800": { main: "Clear", icon: "mdi-weather-sunny", readableName: "Céu Limpo" },
    "801": { main: "Clouds", icon: "mdi-weather-partly-cloudy", readableName: "Poucas Nuvens" },
    "802": { main: "Clouds", icon: "mdi-weather-partly-cloudy", readableName: "Nuvens Esparsas" },
    "803": { main: "Clouds", icon: "mdi-weather-partly-cloudy", readableName: "Nuvens Quebradas" },
    "804": { main: "Clouds", icon: "mdi-weather-partly-cloudy", readableName: "Nuvens Encobertas" },
    "000": { main: "Unknown", icon: "mdi-weather-question-mark", readableName: "Clima Desconhecido" }, // Fallback
};
